JCN-302 crear package
janis-commerce/vtex-account-processes pull request #1
Opened 2020-08-06 20:58 UTC by gastonpereyra

**LINK AL TICKET**
https://fizzmod.atlassian.net/browse/JCN-302

**DESCRIPCIÓN DEL REQUERIMIENTO**

*Introducción*

En el servicio VTEX-Commerce se creó una API para actualizar los estados de los procesos, como la importación de marcas o la publicación de stock, y tener acceso fácil y rápido a cualquier información que estos le puedan proveer. Es por esta razón que se necesitan que los distintos procesos relacionados con VTEX le comuniquen el cambio de estado a esa API. Y el proceso seria similar en todos.

*Requerimiento*

Se necesita:

* Crear un package VTEX-ACCOUNT-PROCESSES 
* Que ese package tenga un método que facilite la llamada a la siguiente API

```yaml
service: vtex-commerce
namespace: account-process
method: update
```
* Se recomienda usar el package https://github.com/janis-commerce/microservice-call
* Tener en cuenta los parametros que esa API puede recibir

**DESCRIPCIÓN DE LA SOLUCIÓN**
Se desarrollaron los requerimientos solicitados

2020-08-07 16:01 UTC, maguimarijuan requested changes

2020-08-07 16:01 UTC, maguimarijuan commented on README.md
> +        * `accountId` : *STRING* VTEX Account ID in VTEX-Commerce
Capaz le podemos poner `objectId` para que quede más claro :thinking:

2020-08-07 16:01 UTC, maguimarijuan commented on README.md
> +        * `options` : *OBJECT*, **OPTIONAL**, Extra Options, for example start Date
No me queda claro por qué el start date es una opción :thinking: Porque si solo le está avisando el estado del proceso, le está avisando cuando empezó? No me queda claro la diferencia entre `content` y `options`

2020-08-07 16:01 UTC, maguimarijuan commented on README.md
> +* `startDate`: *BOOLEAN*, to add an Date-Now ISO-String, for marking the start of the process
mmm, como super mega sugerencia, no sería mejor: 
``startDate`: *BOOLEAN*, to add an Date-Now ISO-String, to indicate the start of the process`
Creo que no entiendo si se indica o se si settea, va acompañado del comentario anterior

2020-08-07 16:01 UTC, maguimarijuan commented on README.md
> +        message: 'Account not foudn'
Tenes un typo acá: foudn -> found

2020-08-07 16:01 UTC, maguimarijuan commented on lib/helpers/validate.js
> +	 * @param {*} session
Este jdoc te quedo incompleto en cuanto al tipo de datos de los parámetros que recibe el método

2020-08-07 16:01 UTC, maguimarijuan commented on lib/helpers/validate.js
> +	 * @param {*} session
Idem para todos los jdocs de este archivo

2020-08-07 16:01 UTC, maguimarijuan commented on lib/helpers/validate.js
> +	 * Validate Params formake a successufully request to VTEX-Commerce Account Process API
creo que esto se escribe así: 
 Validate Params to make a successuful request to VTEX-Commerce Account Process API

2020-08-07 16:01 UTC, maguimarijuan commented on lib/helpers/validate.js
> +module.exports = class ValidateAccountProcess {
No me gusta el nombre de esta clase, yo le pondría algo como AccountProcessValidator. Siempre creo que es mejor que las clases tengan nombres sustantivos, los atributos nombres adjetivos y los métodos nombres verbos. No sé, si es más una opinión o una convención. Creo que para mantener una linea es mejor que le cambies el nombre a algo parecido a lo que te sugiero que vos consideres.

2020-08-07 16:01 UTC, maguimarijuan commented on lib/helpers/validate.js
> +		if(!this.isString(accountId))
Capaz es mejor que valide si es un `objectId` por qué no usamos el paquete de superstruct? Entiendo igual, que sería más complicado definir los códigos de error, asique puede que no sea una buena idea. De igual manera, supongo y entiendo que la api de vtex-commerce tendrá el struct correspondiente. No obstante, no me parece mal dejarlo como una sugerencia :)

2020-08-07 16:01 UTC, maguimarijuan commented on lib/vtex-account-processes.js
> +	 * @param {object=} content Extra Data to inform
Creo que el = te quedó de más?

2020-08-07 16:06 UTC, gastonpereyra commented on lib/vtex-account-processes.js
> +	 * @param {object=} content Extra Data to inform
Estuve buscando en Docu sobre JSDocs y vi que los opcionales los marcan asi con el =

2020-08-07 16:07 UTC, gastonpereyra commented on lib/helpers/validate.js
> +		if(!this.isString(accountId))
Claro, no use superstruct porque se rompe si no valida, y seria dificil settear el código de error, pero agrego lo de objectId no es complicado

2020-08-07 16:16 UTC, maguimarijuan commented on lib/vtex-account-processes.js
> +	 * @param {object=} content Extra Data to inform
Sabes que cuando lo leí creía que iba por ahí? por eso lo dejé como pregunta :+1:

2020-08-07 16:22 UTC, gastonpereyra commented on lib/helpers/validate.js
> +	 * @param {*} session
Deje el "any" ("*") a proposito, para indicar que podria llegar cualquier tipo de dato, y eso luego se valida, no sé si lo hace mas confuso o mas claro

2020-08-10 14:38 UTC, maguimarijuan approved these changes

2020-08-12 16:36 UTC, merged